### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Zumbalamambo** [pacocp/Defect-Detection-in-Nanofibers-by-Image-Classification#1]
Can I get the dataset please?

**Comment by pacocp** [comment]
I'm sorry but I don't have the consent from the researches. Even though, you can find the original images in the [http://ieeexplore.ieee.org/document/7790862/](following paper) and extract the patches manually with the Matlab script.

**Comment by Zumbalamambo** [comment]
@pacocp  can it be used to identify defects from steel?

**Comment by pacocp** [comment]
Sure, you just need to build the dataset

**Comment by Zumbalamambo** [comment]
thank you...

**Comment by Zumbalamambo** [comment]
@pacocp  sorry i have one more doubt... after breaking into pixels, how do we know that defective and non defective pixel ?

**Comment by Zumbalamambo** [comment]
we need to isolate it to two classes like defective, non defective class for classification. Should we isolate it manually by going through each pictures individually?

**Comment by pacocp** [comment]
In my specific case, I had ground truth images. This images tell me if the pixel correspond to defective or a non defective one. So that's why I take, with the script, patches where all the pixels correspond to defective areas in the ground truth images and also corresponding to non defective areas.

If you don't have this kind of ground truth images, you have to take the patches manually.
